#!/usr/bin/env bash

#- fix mac address reverting to orignal
#- paste it in /etc/NetworkManager/NetworkManager.conf

dest=/etc/NetworkManager/NetworkManager.conf
sudo echo "[device]
wifi.scan-rand-mac-address=no

[connection]
ethernet.cloned-mac-address=preserve
wifi.cloned-mac-address=preserve">>$dest
