#!/usr/bin/env bash
#- generate ssh key for for access to git
ssh-keygen -t ed25519 -C "itszet1o1@gmail.com"
eval "$(ssh-agent -s)" 
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub
ssh -T git@github.com  

