#!/usr/bin/env bash


out() { printf "$1$2\e[0m\n"; }
msg() { out "\n\e[1;34m#--" "$@"; }
inf() { out "\e[0;2m--" "$@"; }

msg "installing sublime to system"
inf "adding sublime key.."
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null

inf "adding sublime repo.."
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

inf "fetching & configuring sublime pkg.."
sudo apt-get update
sudo apt-get install -y apt-transport-https
sudo apt-get install -y sublime-text
