#!/usr/bin/env bash
# set default interface to "graphical mode" OR "TTY mode"
while getopts "t1:g1:i" opt; 
do
	case $opt in
	t) #set default boot to tty mode
		systemctl set-default multi-user.target
		;;
	g) #set default boot to graphical mode
		systemctl set-default graphical.target
		;;
	m) #get current mode/taret
		systemctl get-default
		;;
	esac
done

