#!/usr/bin/env bash

out() { printf "$1$2\e[0m\n"; }
msg() { out "\n\e[1;34m#--" "$@"; }
inf() { out "\e[0;2m--" "$@"; }

ipFwdP () {
	msg "ip fwd persistent"
	inf "set net.ipv4.ip_forward=1"
	sudo nano /etc/sysctl.conf
	inf "applying changes"
	sudo sysctl -p && sudo systemctl restart networking
}


sudo iptables -P FORWARD ACCEPT
sudo sysctl -w net.ipv4.ip_forward=1

#sudo echo 1 > /proc/sys/net/ipv4/ip_forward


inf "ip fwd status.."
cat /proc/sys/net/ipv4/ip_forward

