#!/usr/bin/env bash
scriptPath="$(readlink -f "${BASH_SOURCE[0]:-$0}")"
scriptDir="$(dirname "$scriptPath")"
scriptName=${0##*/}
# import helper/logging lib, exit if unavailable
source "${scriptDir}/libxlvini" || {
    echo "'libxlvini' not found in $scriptDir; please ensure it exists for proper msg display"
}

# ==========================================
# SINGLE INSTANCE LOCK
# ==========================================
# Open file descriptor 9 and attach it to a lock file in the temporary directory
lock_file="${TMPDIR:-/tmp}/${scriptName}.lock"
touch "$lock_file"
trap 'rm -f "$lock_file"' EXIT
exec 9>"$lock_file"

# Try to get an exclusive, non-blocking lock. If it fails, another instance is running.
if ! flock -n 9; then
    serr "Another instance of $scriptName is already running. Exiting."
    exit 1
fi
# ==========================================

if [ -d /x.obs/ ]; then
    cd /x.obs/
elif [ -d ~/x.obs/ ]; then
    cd ~/x.obs/
elif [ -d /x/obs/ ]; then
    cd /x/obs/
elif [ -d ~/x/obs/ ]; then
    cd ~/x/obs/
else
    serr "Dir 'obs' not found!"
    exit 1
fi

$scriptDir/gitx sync --safe-dir -c -b main
