#!/usr/bin/env bash

out() { printf "$1$2\e[0m\n"; }
msg() { out "\n\e[1;34m#--" "$@"; }
inf() { out "\n\e[0;2m--" "$@"; }

#- display and execute the command
srun() { echo $1; $1; }



inf "#- clf default dirs \n~/.cloudflared  |  /etc/cloudflared  |  /usr/local/etc/cloudflared\n"

inf "#- Authenticate cloudflared"
srun "cloudflared tunnel login"

#Running this command will:
#Open a browser window and prompt you to log in to your Cloudflare account. After logging in to your account, select your hostname.
#Generate an account certificate, the cert.pem file, in the default cloudflared directory.
#cloudflared tunnel login


inf "#- Create a tunnel and give it a name"
cmd="cloudflared tunnel create <NAME>"
#echo $cmd
read -p "$cmd: " NAME
cmd=${cmd/<NAME>/$NAME}
srun "$cmd"

#Running this command will:
#Create a tunnel by establishing a persistent relationship between the name you provide and a UUID for your tunnel. At this point, no connection is active within the tunnel yet.
#Generate a tunnel credentials file in the default cloudflared directory.
#Create a subdomain of .cfargotunnel.com.

#From the output of the command, take note of the tunnel’s UUID and the path to your tunnel’s credentials file.
#Confirm that the tunnel has been successfully created by running:
srun "cloudflared tunnel list"
#read -p "Tunnel-UUID: " TunnelUUID
TunnelUUID=$(echo -e $(cloudflared tunnel list| grep -iw $NAME | awk '{print $1}'))
echo $TunnelUUID

inf "#- Create a configuration file"
#Create a configuration file in your .cloudflared directory using any text editor. This file will configure the tunnel to route traffic from a given origin to the hostname of your choice.
#Add the following fields to the file:
clfConf="$HOME/.cloudflared/config.yaml"

#If you are connecting an application-
echo -e "
tunnel: $NAME
credentials-file: /root/.cloudflared/$TunnelUUID.json
ingress:
  - hostname: example.com
    service: http://localhost:80


">$clfConf

#If you are connecting a network-
#echo "
#tunnel: <Tunnel-UUID>
#credentials-file: /root/.cloudflared/$TunnelUUID.json
#warp-routing:
#	enabled: true
#">$clfConf

#Confirm that the configuration file has been successfully created by running:
srun "cat $clfConf"


inf "5.Start routing traffic"
#Now assign a CNAME record that points traffic to your tunnel subdomain.
#If you are connecting an application-
cmd="cloudflared tunnel route dns <UUID or NAME> <hostname>"
echo $cmd
read -p "$cmd: " $hostname 
cmd=${cmd/<hostname>/$hostname}
srun "$cmd"

#If you are connecting a network-
#Add the IP/CIDR you would like to be routed through the tunnel.
#cloudflared tunnel route ip add <IP/CIDR> <UUID or NAME>
#cloudflared tunnel route ip show

inf "6.Run the tunnel"
#Run the tunnel to proxy incoming traffic from the tunnel to any number of services running locally on your origin.
cmd="cloudflared tunnel run <UUID or NAME>"
cmd=${cmd/<UUID or NAME>/$NAME}
srun "$cmd"

#If your configuration file has a custom name or is not in the .cloudflared directory, add the --config flag and specify the path.
#cloudflared tunnel --config /path/your-config-file.yaml run

inf "7. Check the tunnel"
#Your tunnel configuration is complete! If you want to get information on the tunnel you just created, you can run:
srun "cloudflared tunnel info"
