#!/usr/bin/env bash

out() { printf "$1$2\e[0m\n"; }
msg() { out "\n\e[1;34m#--" "$@"; }
inf() { out "\e[0;2m--" "$@"; }
err() {
    out "\e[0;31m!!" "$@"
    exit 1
}

scriptPath="$(readlink -f ${BASH_SOURCE[0]:-$0})"
scriptDir="$(dirname "${scriptPath}")"
scriptName=${0##*/}
source "${scriptDir}/libxlvini"

PKG_CATEGORY=(
    pkg_user
    pkg_ops
    pkg_firmware
    pkg_user_gui
    pkg_recovery
    pkg_sys
    pkg_build
    pkg_dev
    pkg_devs
    pkg_util
    pkg_net
    pkg_tool
    pkg_tools
    pkg_srv
    pkg_dep
)

pkg_sys=(
    zram-tools
    lvm2
    btrfs-progs btrbk
    memtest86+
)

pkg_user=(
    jq
    rsync
    git
    fzf glow
    tree
    ranger
    tmux

    lm-sensors
    xdotool
    cmatrix

    rclone
    borgbackup
)
pkg_user_dev=(
    minicom
    android-sdk-platform-tools 
    adb
    scrcpy

    figlet
)

pkg_ops=(
    keepalived

    caddy
    grafana prometheus
    pdns-server pdns-recursor
    pdns-backend-geoip
    pdns-backend-sqlite3 sqlite3
    # pdns-backend-mysql mariadb-server

    postgresql postgresql-contrib redis-server
)
pkg_ops_cli=(
    prometheus-node-exporter
)
pkg_firmware=(
    intel-microcode
    amd64-microcode
    firmware-linux-nonfree
    firmware-misc-nonfree
    firmware-realtek
    firmware-iwlwifi
    dbus-x11
)
pkg_user_gui=(
    libnotify-bin
    libfuse2t64

    zsh zsh-autosuggestions zsh-syntax-highlighting

    gnome-shell-extensions gnome-shell-extension-prefs gnome-shell-extension-manager
    gdm3 gnome-session gnome-shell

    fonts-firacode
    fonts-font-awesome
    fonts-lato
    fonts-noto-core
    baobab
    gparted
    vlc

    pavucontrol
    remmina
    #timeshift	bleachbit
)
pkg_build=(
    bc
    flex
    bison
    dwarves
    xz-utils
    build-essential
    zlib1g
    zlib1g-dev
    lib32z1
    ncurses-dev
    libncurses-dev
    libssl-dev
    libelf-dev

    gcc-aarch64-linux-gnu
    gcc-arm-linux-gnueabi
)
pkg_devops=(
    ansible terraform
    jenkins # circle ci

    vault
)
pkg_devs=(
    
    qemu-user-static binfmt-support

    pip

    cockpit
    qemu-kvm libvirt-daemon-system libvirt-clients virt-manager
    #- CPU architecture emulators, For bridged networking
    #qemu-system bridge-utils
)
pkg_graphics=(
    ffmpeg
    imagemagick
)
pkg_recovery=(
    testdisk
)
pkg_util=(
    x11-utils

)
pkg_net_sys=(
    ifmetric
    dnsmasq
    hostapd
    wpasupplicant
)
pkg_net_util=(
    curl
    ethtool
    iproute2
    iputils-arping
    isc-dhcp-server #dhcpd|dhcp
    iw
    #net-tools 	#- depreciated as iproute2 appreciated!!
)
pkg_net_diagnostic=(
    mesa-utils
)
pkg_net_tool=(
    hping3
    ipcalc
    iperf3
    macchanger
    nmap
    tcpdump
    usbip
)
pkg_net_sec=(
    cowpatty
    dsniff
    mdk3 mdk4
    tshark

    wordlists

    #archivemount libfuse-dev

    #tor proxychains
)

pkg_srv=(
    openssh-server #- access
    avahi-daemon avahi-utils
)
pkg_srv_file=(
    sshfs
    samba
    nfs-common nfs-kernel-server
)
pkg_srv_bundle=(
    #- databases
    mariadb-server mariadb-client ghostscript
    
    openssl
    
    #- web server
    nginx 
    php php-cgi php-fpm php-mysql libapache2-mod-php 

    #- php-perf.modules
    php-apcu php-memcached php-redis

    #- php.modules
    php-common php-curl php-gd php-mbstring php-ctype php-dom php-fileinfo php-json php-simplexml php-pdo-mysql php-posix php-xml php-xmlreader php-xmlwriter php-zip

    #- php.recommended
    php-bz2 php-intl php-exif php-gmp php-imagick

    #- php-required for spec app
    php-ldap php-smbclient php-ftp php-imap php-bcmath

    #not found
    # php-filter php-hash php-libxml php-openssl php-session php-zlib
)
pkg_dep=()

pkg_extra=(
    virtualbox
    kicad
)


pkgInstAllSig=0
pkgNo=()
yesSig=0
extraModSig=0

runSig() {
    local fun_name="$1"
    local fun_sigVar="${fun_name}Sig"

    if [[ "${!fun_sigVar}" == 1 || "${!fun_sigVar,,}" == 1 ]]; then
        # Execute the function
        $fun_name
    fi
}

PKG_list() {
    num=1
    for pkgCat in "${PKG_CATEGORY[@]}"; do
        printf "\e[0;2m$num. $pkgCat: \e[0m"
        pkgArrayName="${pkgCat}[@]"
        for pkg in "${!pkgArrayName}"; do
            printf "$pkg "
        done
        printf "\n"
        num=$((num + 1))
    done
}

PKG_setup() {
    if [[ $pkgInstAllSig == 1 ]]; then
        pkgRoot=()
        num=1
        inf "Preparing full install pkg list.."
        for pkgCat in "${PKG_CATEGORY[@]}"; do
            printf "\e[0;2m$num. $pkgCat: \e[0m"
            pkgArrayName="${pkgCat}[@]"
            for pkg in "${!pkgArrayName}"; do
                pkgRoot+=("$pkg")
                #pkgRoot=($pkg "${pkgRoot[@]}")
                printf "$pkg "
            done
            printf "\n"
            num=$((num + 1))
        done
    elif [[ -n $pkgNo ]]; then
        pkgRoot=()
        num=1
        inf "Preparing full install pkg list.."

        # Convert $pkgNo into an array for easy comparison
        IFS=',' read -ra pkgNoArray <<<"$pkgNo"

        for pkgCat in "${PKG_CATEGORY[@]}"; do
            # Check if $num is in $pkgNoArray
            if [[ " ${pkgNoArray[@]} " =~ " $num " ]]; then
                printf "\e[0;2m$pkgCat: \e[0m"
                pkgArrayName="${pkgCat}[@]"
                for pkg in "${!pkgArrayName}"; do
                    pkgRoot+=("$pkg")
                    printf "$pkg "
                done
                printf "\n"
            fi
            num=$((num + 1))
        done
    else
        err "No package category defined!!\nSpecify using -p <category no>"
        return
    fi
}

# Parse command-line options
while [[ $# -gt 0 ]]; do
    case "$1" in
    -y | --yes) # Proceed without confirmation
        yesSig=1
        shift
        ;;
    -l) # List available package categories
        PKG_list
        exit
        ;;
    -a) # Install packages from all available categories
        pkgInstAllSig=1
        shift
        ;;
    -p) # Define category numbers to install packages from
        pkgNo=$2
        shift 2
        ;;
    --extra) # Install extra package modules
        extraModSig=1
        shift
        ;;
    *) # Invalid option
        err "Invalid option: $1"
        exit 1
        ;;
    esac
done
PKG_setup

# Initialize repository updates
#apt update
msg "Installing defined packages"
printf "\e[0;2mPackages: \e[0m"
echo -e ${pkgRoot[@]}
printf "\n"
# Confirm before proceeding
if [[ $yesSig != 1 ]]; then
    read -p "Press Enter to continue..."
fi
apt install -y "${pkgRoot[@]}"

# Package scripts
if [[ $extraModSig == 1 ]]; then
    inf "Installing extra package modules.."
    # Add your package installation functions here if needed
fi
