#!/usr/bin/env bash

scriptPath="$(readlink -f ${BASH_SOURCE[0]:-$0})"
scriptDir="$(dirname "${scriptPath}")"
scriptName=${0##*/}

source "${scriptDir}/libxlvini"

case $1 in
java)
    shift
    jar_src="$(dirname $(realpath $(xbin -r gnirehtet)))/gnirehtet.jar"
    
    [[ -f "${jar_src}" ]] || { swrn "gnirehtet.jar not found!"; exit 1; }

    sinf "java"
    java -jar "${jar_src}" "${@}"
    ;;
*)
    sinf "rust"
    xbin gnirehtet "${@}"
    ;;
esac
