#!/usr/bin/env bash

rsync --exclude={"/dev/*","/home/*/.cache/*","/lost+found","/media/*","/mnt/*","/proc/*","/*/.cache/*","/run/*","/sys/*","/tmp/*","/var/cache/apt/archives/*","/var/lib/apt/lists/*","/var/log/*","/xlvini/mnt/*","xlvini/mnt/*",".Trash-*"} "${@}"